<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-R9GCIVMV" ignored="0" name="iannotation" tests="15" failures="3" timestamp="2022-09-24T08:55:40 IST" time="0.087" errors="0">
  <testcase name="test1" time="0.008" classname="retryLogic.testFailed1">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="retryLogic.testFailed1">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="retryLogic.testFailed1">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.0" classname="retryLogic.testFailed1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogic.testFailed1.test1(testFailed1.java:9)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="0.001" classname="retryLogic.testFailed1"/>
  <testcase name="test3" time="0.001" classname="retryLogic.testFailed1">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.001" classname="retryLogic.testFailed1">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.0" classname="retryLogic.testFailed1">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.001" classname="retryLogic.testFailed1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogic.testFailed1.test3(testFailed1.java:17)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.001" classname="retryLogic.testFailed1"/>
  <testcase name="test5" time="0.001" classname="retryLogic.testFailed1">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase name="test5" time="0.001" classname="retryLogic.testFailed1">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase name="test5" time="0.001" classname="retryLogic.testFailed1">
    <skipped/>
  </testcase> <!-- test5 -->
  <testcase name="test5" time="0.002" classname="retryLogic.testFailed1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retryLogic.testFailed1.test5(testFailed1.java:25)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase name="test6" time="0.001" classname="retryLogic.testFailed1"/>
</testsuite> <!-- iannotation -->
